import Head from "next/head";
import Logo from "./components/Logo";
import styles from "../styles/index.module.scss";

const Custom404 = () => {
  return (
    <>
      <Head>
        <title>404</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <html lang="es" />
      </Head>
      <section className={styles.cuatroCeroCuatro}>
        <Logo />
        <h1>404 - Página no encontrada</h1>
        <p>Lo sentimos, la página que estás buscando no existe.</p>
      </section>
    </>
  );
};

export default Custom404;
